version: "3.7"
services:
  redis:
    image: redis:alpine
    container_name: queues_redis
    ports:
        - 6379:6379
    networks:
        - queue-networks

networks:
  queue-networks:
    driver: bridge
